Repository turkey-kim/8lack, pull requests merged in 2023-11, with the labels that each got.

#7 [#6] 네비게이션바 & 사이드바 디자인
  src/App.tsx
  src/api/.gitkeep
  src/assets/.gitkeep
  src/assets/icons/Chat.svg
  src/assets/icons/Logo.png
  src/components/.gitkeep
  src/components/Navigation/Navigation.tsx
  src/components/PrivateChat/PrivateChat.tsx
  src/components/PrivateChat/PrivateChats.tsx
  src/components/SideBar/SideBar.tsx
  src/hooks/.gitkeep
  src/index.tsx
  src/pages/.gitkeep
  src/pages/MyPage.tsx
  src/pages/NotFound.tsx
  src/pages/Users.tsx
  src/styles/.gitkeep
  src/utils/.gitkeep
Labels: feat, design

#11 [#8] 내 정보, 사용자리스트 디자인
  package-lock.json
  package.json
  src/components/MyPage/MyPage.tsx
  src/components/Navigation/Navigation.tsx
  src/index.tsx
  src/pages/MyPage.tsx
  src/pages/Users.tsx
Labels: feat, design

#13 [#3] 로그인/회원가입 기능 추가
  package-lock.json
  package.json
  public/_redirects
  src/App.tsx
  src/api/auth.ts
  src/components/signIn/SignInBox.tsx
  src/components/signUp/SignUpBox.tsx
  src/constant.ts
  src/index.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: feat

#14 [#5] 채팅룸 마크업
  .gitignore
  public/index.html
  src/components/Chat/Chat.data.ts
  src/components/Chat/Chat.tsx
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/Drawer.types.ts
  src/components/MessageList/Message.types.ts
  src/components/MessageList/MessageList.tsx
  src/components/PublicChat/PublicChat.tsx
  src/components/SendMessage/SendMessage.tsx
  src/components/SendMessage/SendMessage.types.ts
  src/components/UserList/UserList.tsx
  src/components/UserList/UserList.types.ts
  src/index.tsx
  src/pages/ChatAll.tsx
  src/pages/ChatRoom.tsx
  src/types/chatroom.types.ts
  tsconfig.json
Labels: feat, design

#19 [#3] 회원가입 아이디 중복체크 기능 추가
  src/api/auth.ts
  src/components/signIn/SignInBox.tsx
  src/components/signUp/SignUpBox.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: feat, design

#21 Feat/#17 그룹채팅방 리스트 마크업 및 디자인
  package-lock.json
  package.json
  src/components/ChatRoomsList/ChatRoomEl.tsx
  src/components/ChatRoomsList/ChatRoomsList.tsx
  src/components/HeaderLayout/HeaderLayout.tsx
  src/components/HeaderLayout/SearchBar.tsx
  src/components/HeaderLayout/TabButton/TabButtons.tsx
  src/components/HeaderLayout/TabButton/TabEl.tsx
  src/components/HeaderLayout/TabButton/TabProps.ts
  src/components/Navigation/Navigation.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/GroupChatList.tsx
  src/styles/GlobalStyles.ts
  src/styles/Theme.ts
  tsconfig.json
Labels: feat, design

#24 [#20] 회원 인증 기능 및 로그아웃 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/auth.ts
  src/components/Navigation/Navigation.tsx
  src/components/signIn/SignInBox.tsx
  src/hooks/useAuthCheck.ts
  src/routes/UserPublicRoute.tsx
  src/states/atom.ts
Labels: feat

#25 [#12] 내 정보 기능 구현
  src/api/mypage.ts
  src/api/users.ts
  src/components/Chat/Chat.tsx
  src/components/Drawer/Drawer.tsx
  src/components/MyPage/MyPage.tsx
  src/components/Users/FavorUserLists.tsx
  src/components/Users/UserLists.tsx
  src/index.tsx
  src/pages/ChatAll.tsx
  src/pages/ChatRoom.tsx
  src/pages/Users.tsx
Labels: fix, feat

#27 [#26] 로그인/회원가입 페이지 폴더구조 정리
  src/hooks/useAuthCheck.ts
  src/pages/SignIn/components/SignInBox.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/components/SignUpBox.tsx
  src/pages/SignUp/index.tsx
  src/routes/UserPublicRoute.tsx
  src/states/atom.ts
Labels: feat, env

#31 [#30] 네비게이션바 수정
  src/api/myChatRoom.ts
  src/components/Navigation/Navigation.tsx
  src/components/PrivateChat/PrivateChat.tsx
  src/components/PrivateChat/PrivateChats.tsx
  src/components/PrivateChat/dummyPrivateRooms.ts
  src/components/SideBar/SideBar.tsx
  src/styles/Theme.ts
Labels: feat

#32 [#28] 홈화면 접속 시 소켓 연결
  src/routes/UserPublicRoute.tsx
  src/states/atom.ts
Labels: feat

#33 [#23]그룹채팅 만들기 모달 마크업 및 디자인
  src/components/GenerateChat/GenerateChat.tsx
  src/components/GenerateChat/UserCell.tsx
  src/components/GenerateChat/UserCells.tsx
  src/components/HeaderLayout/HeaderLayout.tsx
  src/components/HeaderLayout/SearchBar.tsx
  src/components/HeaderLayout/TabButton/TabEl.tsx
  src/styles/GlobalStyles.ts
Labels: feat, design

#36 [#18] 채팅룸 소켓 연결 및 이벤트 처리
  src/api/auth.ts
  src/api/chat.ts
  src/api/mypage.ts
  src/api/users.ts
  src/components/Chat/Chat.data.ts
  src/components/Drawer/Drawer.tsx
  src/components/Drawer/Drawer.types.ts
  src/components/MessageList/Message.types.ts
  src/components/MessageList/MessageList.tsx
  src/components/MyPage/MyPage.tsx
  src/components/Navigation/Navigation.tsx
  src/components/SendMessage/SendMessage.types.ts
  src/components/UserList/UserList.types.ts
  src/constant/constant.ts
  src/contexts/SocketContext.tsx
  src/index.tsx
  src/pages/ChatAll/components/ChatRoomForm.tsx
  src/pages/ChatAll/components/ChatRoomForm.types.ts
  src/pages/ChatAll/components/PublicChat.tsx
  src/pages/ChatAll/index.tsx
  src/pages/ChatRoom.tsx
  src/pages/ChatRoom/components/Chat.tsx
  src/pages/ChatRoom/components/MessageList.tsx
  src/pages/ChatRoom/components/SendMessage.tsx
  src/pages/ChatRoom/components/UserList.tsx
  src/pages/ChatRoom/index.tsx
  src/pages/SignIn/components/SignInBox.tsx
  src/routes/UserPublicRoute.tsx
  src/types/chatroom.types.ts
  src/utils/formatDate.ts
Labels: feat

#37 [#22] 그룹채팅방 생성 모달에서 유저 모두 불러오기, 채팅방 생성하기 로직 구현
  src/api/myChatRoom.ts
  src/api/users.ts
  src/components/ChatRoomsList/ChatRoomEl.tsx
  src/components/ChatRoomsList/ChatRoomsList.tsx
  src/components/ChatRoomsList/chatRoomDummyData.ts
  src/components/GenerateChat/GenerateChat.tsx
  src/components/GenerateChat/UserCells.tsx
  src/components/GenerateChat/dummyUserData.ts
  src/components/HeaderLayout/SearchBar.tsx
  src/routes/UserPublicRoute.tsx
  src/states/atom.ts
  src/types/chatroom.types.ts
Labels: feat

#44 [#43] 폴더구조 변경(사용자 리스트)
  src/components/MyPage/MyPage.tsx
  src/index.tsx
  src/pages/UsersList/components/UserItem.tsx
  src/pages/UsersList/components/UserLists.tsx
  src/pages/UsersList/index.tsx
Labels: env

#46 [#10] 사이드바 - 그룹 채팅 기능 구현
  src/api/myChatRoom.ts
  src/components/GroupChat/GroupChat.tsx
  src/components/GroupChat/GroupChats.tsx
  src/components/PrivateChat/PrivateChat.tsx
  src/components/PrivateChat/PrivateChats.tsx
  src/index.tsx
  src/types/chatroom.types.ts
Labels: feat

#50 [#45] 그룹채팅 생성 모달에서 사용자 검색 기능 추가, 폴더구조 정리
  src/components/GenerateChat/UserCells.tsx
  src/index.tsx
  src/pages/GroupChatList/ChatRoomsList/ChatRoomEl.tsx
  src/pages/GroupChatList/ChatRoomsList/ChatRoomsList.tsx
  src/pages/GroupChatList/ChatRoomsList/chatRoomDummyData.ts
  src/pages/GroupChatList/GroupChatList.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/GenerateChat.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/UserCell.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/UserCells.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/dummyUserData.ts
  src/pages/GroupChatList/HeaderLayout/HeaderLayout.tsx
  src/pages/GroupChatList/HeaderLayout/SearchBar.tsx
  src/pages/GroupChatList/HeaderLayout/TabButton/TabButtons.tsx
  src/pages/GroupChatList/HeaderLayout/TabButton/TabEl.tsx
  src/pages/GroupChatList/HeaderLayout/TabButton/TabProps.ts
Labels: feat, refactor

#52 [#49] 그룹 채팅방 리스트에서 그룹 채팅방 입장 가능 및 입장한 그룹 채팅방은 숨김 처리
  src/api/wholeChatRoom.ts
  src/pages/GroupChatList/ChatRoomsList/ChatRoomEl.tsx
  src/pages/GroupChatList/ChatRoomsList/ChatRoomsList.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/GenerateChat.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/UserCell.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/UserCells.tsx
  src/pages/GroupChatList/HeaderLayout/SearchBar.tsx
Labels: feat

#53 [#34] 나와의 채팅방 생성
  src/api/auth.ts
  src/pages/SignIn/components/SignInBox.tsx
  src/pages/SignUp/components/SignUpBox.tsx
Labels: fix, feat

#55 [#51] 그룹채팅방 검색 및 정렬 기능 추가
  src/pages/GroupChatList/ChatRoomsList/ChatRoomsList.tsx
  src/pages/GroupChatList/GroupChatList.tsx
  src/pages/GroupChatList/GroupChatRoomsLayout/GroupChatRoomEl.tsx
  src/pages/GroupChatList/GroupChatRoomsLayout/GroupChatRoomsLayout.tsx
  src/pages/GroupChatList/GroupChatRoomsLayout/chatRoomDummyData.ts
  src/pages/GroupChatList/HeaderLayout/GenerateChat/GenerateChat.tsx
  src/pages/GroupChatList/HeaderLayout/HeaderLayout.tsx
  src/pages/GroupChatList/HeaderLayout/SearchBar.tsx
  src/pages/GroupChatList/HeaderLayout/TabButton/TabButtons.tsx
  src/pages/GroupChatList/HeaderLayout/TabButton/TabEl.tsx
Labels: feat, refactor, rename

#58 [#47] React Query를 이용한 실시간 업데이트 (그룹채팅방)
  package-lock.json
  package.json
  src/App.tsx
  src/components/GroupChat/GroupChat.tsx
  src/components/GroupChat/GroupChats.tsx
  src/components/PrivateChat/PrivateChat.tsx
  src/components/SideBar/SideBar.tsx
  src/hooks/useRealTimeUpdate.ts
Labels: feat

#56 [#15] 사용자 리스트 즐겨찾기, 개인 채팅창 생성 기능 구현
  package-lock.json
  package.json
  src/pages/UsersList/components/UserItem.tsx
  src/pages/UsersList/components/UserLists.tsx
Labels: feat

#60 [#38] 소켓 동시 연결 시 접속 끊기는 이슈 (임시)해결
  src/App.tsx
  src/api/wholeChatRoom.ts
  src/components/Drawer/Drawer.tsx
  src/contexts/ChatSocketContext.tsx
  src/contexts/ServerSocketContext.tsx
  src/pages/ChatAll/components/ChatRoomForm.tsx
  src/pages/ChatAll/components/ChatRoomForm.types.ts
  src/pages/ChatAll/components/PublicChat.tsx
  src/pages/ChatAll/index.tsx
  src/pages/ChatRoom/components/Chat.tsx
  src/pages/ChatRoom/components/MessageList.tsx
  src/pages/ChatRoom/components/SendMessage.tsx
  src/pages/ChatRoom/components/UserList.tsx
  src/pages/ChatRoom/index.tsx
  src/routes/UserPublicRoute.tsx
Labels: fix, feat

#62 feat: 즐겨찾기 보완
  src/pages/UsersList/components/UserItem.tsx
  src/pages/UsersList/components/UserLists.tsx
  src/states/atom.ts
Labels: feat

#64 [#40] 이전 대화 기록 불러오기 & 최신 메시지 수신 시 스크롤 이동
  src/contexts/ChatSocketContext.tsx
  src/pages/ChatRoom/components/MessageItem.tsx
  src/pages/ChatRoom/components/MessageList.tsx
  src/utils/formatDate.ts
Labels: feat

#66 [#63] 공통 로딩바 애니메이션 기능 추가
  package-lock.json
  package.json
  src/components/LoadingCircle/LoadingCircle.tsx
  src/pages/GroupChatList/GroupChatList.tsx
  src/pages/GroupChatList/GroupChatRoomsLayout/GroupChatRoomEl.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/GenerateChat.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/UserCell.tsx
  src/pages/GroupChatList/HeaderLayout/GenerateChat/UserCells.tsx
  src/pages/GroupChatList/HeaderLayout/HeaderLayout.tsx
  src/pages/GroupChatList/HeaderLayout/SearchBar.tsx
  src/pages/GroupChatList/HeaderLayout/TabButton/TabButtons.tsx
  src/pages/GroupChatList/HeaderLayout/TabButton/TabEl.tsx
Labels: feat

#67 [#48] 개인 채팅방 api 연결
  src/components/PrivateChat/PrivateChat.tsx
  src/components/PrivateChat/PrivateChats.tsx
  src/pages/GroupChatList/GroupChatRoomsLayout/chatRoomDummyData.ts
  src/pages/GroupChatList/HeaderLayout/GenerateChat/dummyUserData.ts
  src/types/chatroom.types.ts
Labels: feat

#69 [#61] 사용자 리스트 기능 구현 보완 (1:1 채팅)
  src/components/PrivateChat/PrivateChat.tsx
  src/pages/UsersList/components/UserItem.tsx
  src/pages/UsersList/components/UserLists.tsx
Labels: fix, feat

#70 [#59] 활동중인 유저 표시 기능 추가
  src/App.tsx
  src/pages/UsersList/components/UserItem.tsx
Labels: fix, feat

#72 [#68] 커스텀 훅 생성 및 1:1 채팅방 리스트 수정
  src/components/GroupChat/GroupChat.tsx
  src/components/GroupChat/GroupChats.tsx
  src/components/PrivateChat/PrivateChat.tsx
  src/components/PrivateChat/PrivateChats.tsx
  src/components/PrivateChat/dummyPrivateRooms.ts
  src/hooks/useSortedSidebarChat.ts
Labels: refactor

#76 [#75] 타입 이름 변경
  src/hooks/useSortedSidebarChat.ts
Labels: fix

#80 [#29] 로그인 페이지 디자인 수정 및 논유저라우터 구현
  src/assets/icons/TextLogo.svg
  src/assets/images/login-background.png
  src/index.tsx
  src/pages/SignIn/components/SignInBox.tsx
  src/pages/SignIn/components/SignUpBox.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/routes/NonUserRoute.tsx
  src/routes/UserPublicRoute.tsx
Labels: feat, design

#85 [#77] 채팅 소켓 상태관리 이슈 해결
  src/api/myChatRoom.ts
  src/contexts/ChatSocketContext.tsx
  src/hooks/useUid.ts
  src/pages/ChatRoom/components/Chat.tsx
  src/pages/ChatRoom/components/ChatHeader.tsx
  src/pages/ChatRoom/components/MessageItem.tsx
  src/pages/ChatRoom/components/MessageList.tsx
  src/pages/SignIn/components/SignUpBox.tsx
Labels: fix

#86 [#82] 홈페이지 추가 및 라우팅 + 네비게이션바 연동
  src/components/Navigation/Navigation.tsx
  src/index.tsx
  src/pages/Home/components/.gitkeep
  src/pages/Home/index.tsx
  src/routes/UserPublicRoute.tsx
Labels: feat

#89 [#83] 사용자 리스트 검색 결과 없을때 화면 수정, 중복 이벤트 방지
  package-lock.json
  package.json
  src/components/MyPage/MyPage.tsx
  src/pages/UsersList/components/UserItem.tsx
  src/pages/UsersList/components/UserLists.tsx
Labels: feat, refactor, design

#93 [#91] 마이페이지에서 uid 훅 사용
  src/components/MyPage/MyPage.tsx
Labels: refactor

#97 [#87] 채팅방 유저 이름 & 접속상태 표시
  src/api/myChatRoom.ts
  src/pages/ChatRoom/components/AddUserModal.tsx
  src/pages/ChatRoom/components/Chat.tsx
  src/pages/ChatRoom/components/MessageItem.tsx
  src/pages/ChatRoom/components/UserList.tsx
Labels: feat, design

#94 [#73] 로딩 스피너 추가 및 사이드바 네비게이션 수정
  src/components/GroupChat/GroupChat.tsx
  src/components/GroupChat/GroupChats.tsx
  src/components/MyPage/MyPage.tsx
  src/components/Navigation/Navigation.tsx
  src/components/PrivateChat/PrivateChat.tsx
  src/components/PrivateChat/PrivateChats.tsx
  src/components/SideBar/SideBar.tsx
Labels: refactor, design

#101 [#99] 404 페이지 생성
  src/App.tsx
  src/index.tsx
  src/pages/NotFound.tsx
  src/pages/NotFound/components/NotFoundBox.tsx
  src/pages/NotFound/index.tsx
Labels: design

#104 [#103] 앱 메타데이터 설정(사이트 이름, favicon) 설정, index.tsx로 이름 변경
  public/8lack_favicon.svg
  public/favicon.ico
  public/index.html
  src/App.css
  src/App.tsx
  src/index.tsx
  src/pages/GroupChatList/GroupChatRoomsLayout/favicon.ico
  src/pages/GroupChatList/GroupChatRoomsLayout/index.tsx
  src/pages/GroupChatList/HeaderLayout/index.tsx
  src/pages/GroupChatList/index.tsx
  src/pages/UsersList/index.tsx
Labels: refactor, design

#105 [#90] 홈페이지 그룹채팅리스트 디자인 추가
  src/pages/Home/components/.gitkeep
  src/pages/Home/components/ChatSection/Card.tsx
  src/pages/Home/components/ChatSection/ChatSection.types.ts
  src/pages/Home/components/ChatSection/SlidingList.tsx
  src/pages/Home/components/ChatSection/chatSection.data.ts
  src/pages/Home/components/ChatSection/index.tsx
  src/pages/Home/components/ChatSection/styledAnimation.ts
  src/pages/Home/index.tsx
  src/routes/UserPublicRoute.tsx
  src/styles/Theme.ts
Labels: design

#110 [#106] 탭 버튼 누를때 기존 캐싱된 데이터 활용, 그룹채팅방 리스트에 windowing 설정
  package-lock.json
  package.json
  src/pages/GroupChatList/GroupChatRoomsLayout/GroupChatRoomEl.tsx
  src/pages/GroupChatList/GroupChatRoomsLayout/index.tsx
  src/pages/GroupChatList/index.tsx
Labels: refactor

#109 [#108] 나와의 채팅방 생성기능 삭제 및 기타 수정
  src/api/auth.ts
  src/constant/constant.ts
  src/pages/SignIn/components/SignInBox.tsx
  src/pages/SignIn/components/SignUpBox.tsx
  src/pages/SignIn/index.tsx
Labels: refactor, design

#111 [#91] 메인페이지 설명 컴포넌트 추가
  src/assets/images/main_background.png
  src/assets/images/main_chat1.png
  src/assets/images/main_chatback.png
  src/assets/images/main_chatroom1.png
  src/assets/images/main_chatroom2.png
  src/assets/images/main_mychat1.png
  src/assets/images/main_mychat2.png
  src/assets/images/main_user1.png
  src/assets/images/main_user2.png
  src/assets/images/main_user3.png
  src/assets/images/main_userbackground.png
  src/pages/Home/components/ChatSection/index.tsx
  src/pages/Home/components/IntroSection/components/ChatRoom.tsx
  src/pages/Home/components/IntroSection/components/Invite.tsx
  src/pages/Home/components/IntroSection/components/MyChat.tsx
  src/pages/Home/components/IntroSection/components/MyInfo.tsx
  src/pages/Home/components/IntroSection/components/User.tsx
  src/pages/Home/components/IntroSection/index.tsx
  src/pages/Home/index.tsx
Labels: design

#112 [#88] 유저 초대&새로운 채팅방 생성 알림 구현, framer-motion 적용
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/api/myChatRoom.ts
  src/api/wholeChatRoom.ts
  src/assets/images/symbol.png
  src/components/GenerateModal/GenerateModal.tsx
  src/contexts/ChatSocketContext.tsx
  src/contexts/ServerSocketContext.tsx
  src/hooks/useChatRoomMutation.ts
  src/pages/ChatRoom/components/Chat.tsx
  src/pages/ChatRoom/components/MessageItem.tsx
  src/pages/ChatRoom/components/MessageList.tsx
  src/pages/Toast/components/ToastItem.tsx
  src/pages/Toast/index.tsx
  src/pages/UsersList/components/UserItem.tsx
  src/states/atom.ts
  src/styles/Theme.ts
  src/types/server.types.ts
Labels: feat, design

#117 [#116] 리팩토링 및 버그 수정
  src/components/GroupChat/GroupChat.tsx
  src/components/Navigation/Navigation.tsx
  src/components/PrivateChat/PrivateChat.tsx
  src/components/PrivateChat/PrivateChats.tsx
  src/components/SideBar/SideBar.tsx
  src/hooks/useRealTimeUpdate.ts
  src/hooks/useUid.ts
  src/pages/Home/components/HeaderSection/HeaderSection.tsx
  src/pages/Home/index.tsx
Labels: fix, refactor

#119 [#118] 홈,회원가입페이지 경고메시지 제거
  src/pages/Home/components/ChatSection/Card.tsx
  src/pages/Home/components/ChatSection/SlidingList.tsx
  src/pages/SignIn/components/SignUpBox.tsx
Labels: fix, refactor

#120 [#113] 채팅방안 유저 변화 시 유저목록 강제 리패치 & 리팩토링
  package-lock.json
  src/components/Avatars/index.tsx
  src/components/Modal/Modal.types.ts
  src/components/Modal/index.tsx
  src/contexts/ChatSocketContext.tsx
  src/hooks/useChatRoomRefetch.ts
  src/pages/ChatRoom/components/Chat.tsx
Labels: fix, refactor

#122 [#115] 불필요한 코드 삭제
  package-lock.json
  src/components/MyPage/MyPage.tsx
  src/pages/Home/components/IntroSection/components/ChatRoom.tsx
  src/pages/Home/components/IntroSection/components/Invite.tsx
  src/pages/Home/components/IntroSection/components/MyChat.tsx
  src/pages/Home/components/IntroSection/components/User.tsx
  src/pages/UsersList/components/UserItem.tsx
  src/pages/UsersList/components/UserLists.tsx
  src/pages/UsersList/index.tsx
Labels: comment

#125 [#113] 메모이제이션 적용, 웹팩 번들링, ui 수정
  config-overrides.js
  package-lock.json
  package.json
  public/logo192.png
  public/logo512.png
  src/App.tsx
  src/components/Drawer/index.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastItem.tsx
  src/contexts/ChatSocketContext.tsx
  src/contexts/ServerSocketContext.tsx
  src/index.tsx
  src/pages/ChatRoom/components/Chat.tsx
  src/pages/ChatRoom/components/ChatHeader.tsx
  src/pages/ChatRoom/components/MessageItem.tsx
  src/pages/ChatRoom/components/MessageList.tsx
  src/pages/ChatRoom/components/SendMessage.tsx
  src/pages/ChatRoom/components/UserList.tsx
  src/pages/GroupChatList/HeaderLayout/SearchBar.tsx
  src/pages/GroupChatList/HeaderLayout/TabButton/TabEl.tsx
  src/pages/SignIn/components/SignInBox.tsx
  src/pages/UsersList/components/UserItem.tsx
  src/types/chatroom.types.ts
Labels: refactor, design

#124 docs: README 추가
  README.md
Labels: docs
